apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: swagger-
resources:
- deployment.yaml
- sa.yaml
images:
- name: ghcr.io/doodlescheduling/apollo-controller
  newTag: v2.2.0
